#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib.sh
source "$PROJECT_DIR/scripts/lib.sh"
load_config

[[ "$(id -u)" -eq 0 ]] || die "run as root"

ARCH="$(detect_arch)"
MY_IP="$(current_ip)"
MY_NAME="$(node_name_by_ip "$MY_IP" || true)"
[[ -n "$MY_NAME" ]] || die "current node IP $MY_IP is not present in CLUSTER_NODES"
apply_node_overrides "$MY_NAME"

is_true() {
  [[ "${1,,}" == "true" || "$1" == "1" || "${1,,}" == "yes" || "${1,,}" == "on" ]]
}

install_prereqs() {
  log "install prerequisites"
  if command -v dnf >/dev/null 2>&1 || command -v yum >/dev/null 2>&1; then
    pkg_install gcc make bison flex readline-devel zlib-devel openssl-devel libuuid-devel libicu-devel perl tar gzip python3 python3-devel python3-pip sudo chrony
  elif command -v apt-get >/dev/null 2>&1; then
    pkg_install gcc make bison flex libreadline-dev zlib1g-dev libssl-dev uuid-dev libicu-dev perl tar gzip python3 python3-dev python3-pip python3-venv sudo chrony
  else
    die "no supported package manager found"
  fi
}

configure_os() {
  log "configure operating system baseline"

  if [[ -n "${OS_TIMEZONE:-}" ]] && command -v timedatectl >/dev/null 2>&1; then
    timedatectl set-timezone "$OS_TIMEZONE" || true
  fi

  if is_true "$OS_ENABLE_CHRONY"; then
    systemctl enable --now chronyd >/dev/null 2>&1 || systemctl enable --now chrony >/dev/null 2>&1 || true
  fi

  if is_true "$OS_DISABLE_TRANSPARENT_HUGEPAGE"; then
    cat >/etc/systemd/system/disable-thp.service <<'EOF'
[Unit]
Description=Disable Transparent Huge Pages
DefaultDependencies=no
After=sysinit.target local-fs.target
Before=postgresql.service patroni.service

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'test -f /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/enabled || true; test -f /sys/kernel/mm/transparent_hugepage/defrag && echo never > /sys/kernel/mm/transparent_hugepage/defrag || true'

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now disable-thp.service >/dev/null 2>&1 || true
  fi

  if is_true "$OS_APPLY_SYSCTL"; then
    cat >/etc/sysctl.d/99-postgresql-ha.conf <<'EOF'
fs.aio-max-nr = 1048576
fs.file-max = 76724600
fs.nr_open = 20480000
net.core.netdev_max_backlog = 10000
net.core.rmem_default = 262144
net.core.rmem_max = 4194304
net.core.somaxconn = 4096
net.core.wmem_default = 262144
net.core.wmem_max = 4194304
net.ipv4.ip_local_port_range = 40000 65535
net.ipv4.tcp_fin_timeout = 5
vm.overcommit_memory = 0
vm.swappiness = 10
EOF
    sysctl --system >/dev/null || true
  fi

  if is_true "$OS_APPLY_LIMITS"; then
    cat >/etc/security/limits.d/99-postgresql-ha.conf <<EOF
${POSTGRES_OS_USER} soft nproc unlimited
${POSTGRES_OS_USER} hard nproc unlimited
${POSTGRES_OS_USER} soft nofile 102400
${POSTGRES_OS_USER} hard nofile 102400
${POSTGRES_OS_USER} soft stack unlimited
${POSTGRES_OS_USER} hard stack unlimited
${POSTGRES_OS_USER} soft core unlimited
${POSTGRES_OS_USER} hard core unlimited
${POSTGRES_OS_USER} soft memlock unlimited
${POSTGRES_OS_USER} hard memlock unlimited
EOF
  fi

  if is_true "$OS_MANAGE_SELINUX" && command -v getenforce >/dev/null 2>&1; then
    setenforce 0 >/dev/null 2>&1 || true
    if [[ -f /etc/selinux/config ]]; then
      sed -i 's/^SELINUX=.*/SELINUX=permissive/' /etc/selinux/config
    fi
  fi
}

configure_firewall() {
  if is_true "$OS_OPEN_FIREWALL_PORTS" && command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld; then
    log "open firewall ports for PostgreSQL HA"
    firewall-cmd --permanent --add-port="${POSTGRES_PORT}/tcp"
    firewall-cmd --permanent --add-port="${PATRONI_PORT}/tcp"
    firewall-cmd --permanent --add-port="${ETCD_CLIENT_PORT}/tcp"
    firewall-cmd --permanent --add-port="${ETCD_PEER_PORT}/tcp"
    firewall-cmd --reload
  fi
}

create_users_dirs() {
  log "create postgres user and directories"
  id "$POSTGRES_OS_USER" >/dev/null 2>&1 || useradd -m -U "$POSTGRES_OS_USER"
  mkdir -p "$PG_PREFIX" "$PG_DATA" "$PG_WAL_ARCHIVE" "$PG_BACKUP" "$ETCD_DATA" "$PATRONI_HOME" "$PATRONI_LOG_DIR"
  mkdir -p /var/run/postgresql
  chown -R "$POSTGRES_OS_USER:$POSTGRES_OS_USER" "$PG_PREFIX" "$(dirname "$PG_DATA")" "$(dirname "$PG_WAL_ARCHIVE")" "$PG_BACKUP" "$PATRONI_LOG_DIR"
  chown "$POSTGRES_OS_USER:$POSTGRES_OS_USER" /var/run/postgresql
  chmod 775 /var/run/postgresql
  chmod 700 "$PG_DATA" "$(dirname "$PG_WAL_ARCHIVE")" "$PG_BACKUP"
}

write_postgres_env() {
  log "write postgres environment file"
  local pg_home
  pg_home="$(getent passwd "$POSTGRES_OS_USER" | cut -d: -f6)"
  [[ -n "$pg_home" ]] || pg_home="/home/${POSTGRES_OS_USER}"
  cat >"${pg_home}/.pgev" <<EOF
# PostgreSQL HA environment generated by installer.
export PGHOME=${PG_PREFIX}
export PGDATA=${PG_DATA}
export PGPORT=${POSTGRES_PORT}
export PGDATABASE=${PGDATABASE}
export PGUSER=${POSTGRES_SUPERUSER}
export PGHOST=/var/run/postgresql
export PATRONI_CONFIG=${PATRONI_HOME}/patroni.yml
export ETCDCTL_ENDPOINTS=$(etcd_client_endpoints)
export PATH=\$PGHOME/bin:/opt/patroni-venv/bin:${ETCD_BIN_DIR}:\$PATH
export LD_LIBRARY_PATH=\$PGHOME/lib:\${LD_LIBRARY_PATH:-}
EOF
  chown "$POSTGRES_OS_USER:$POSTGRES_OS_USER" "${pg_home}/.pgev"
  chmod 0640 "${pg_home}/.pgev"
  if ! grep -q 'source ~/.pgev' "${pg_home}/.bashrc" 2>/dev/null; then
    printf '\n# PostgreSQL HA environment\n[ -f ~/.pgev ] && source ~/.pgev\n' >> "${pg_home}/.bashrc"
  fi
  chown "$POSTGRES_OS_USER:$POSTGRES_OS_USER" "${pg_home}/.bashrc"
}

install_postgres() {
  if [[ -x "$PG_PREFIX/bin/postgres" ]]; then
    log "PostgreSQL already installed at $PG_PREFIX"
    return 0
  fi
  local tgz="$PROJECT_DIR/packages/postgresql-${POSTGRES_VERSION}.tar.gz"
  [[ -f "$tgz" ]] || die "missing $tgz; run scripts/download-packages.sh first"
  log "build PostgreSQL $POSTGRES_VERSION"
  local build_dir="/tmp/postgresql-${POSTGRES_VERSION}-build"
  rm -rf "$build_dir"
  mkdir -p "$build_dir"
  tar -xzf "$tgz" -C "$build_dir" --strip-components=1
  cd "$build_dir"
  ./configure --prefix="$PG_PREFIX" --with-openssl --with-zlib --with-uuid=e2fs
  make -j"$(nproc)"
  make install
  cd contrib
  make -j"$(nproc)"
  make install
  chown -R "$POSTGRES_OS_USER:$POSTGRES_OS_USER" "$PG_PREFIX"
}

install_etcd() {
  if [[ -x "$ETCD_BIN_DIR/etcd" ]]; then
    log "etcd already installed at $ETCD_BIN_DIR"
    return 0
  fi
  local tgz="$PROJECT_DIR/packages/etcd-${ETCD_VERSION}-linux-${ARCH}.tar.gz"
  [[ -f "$tgz" ]] || die "missing $tgz; run scripts/download-packages.sh first"
  log "install etcd $ETCD_VERSION"
  local tmp="/tmp/etcd-${ETCD_VERSION}"
  rm -rf "$tmp"
  mkdir -p "$tmp"
  tar -xzf "$tgz" -C "$tmp" --strip-components=1
  mkdir -p "$ETCD_BIN_DIR"
  install -m 0755 "$tmp/etcd" "$ETCD_BIN_DIR/etcd"
  install -m 0755 "$tmp/etcdctl" "$ETCD_BIN_DIR/etcdctl"
  install -m 0755 "$tmp/etcdutl" "$ETCD_BIN_DIR/etcdutl"
}

install_patroni() {
  log "install Patroni venv"
  if python3 -m venv /opt/patroni-venv >/dev/null 2>&1; then
    :
  else
    python3 -m pip install --upgrade --user virtualenv
    python3 -m virtualenv /opt/patroni-venv
  fi
  if compgen -G "$PROJECT_DIR/packages/wheels/*.whl" >/dev/null; then
    /opt/patroni-venv/bin/pip install --no-index --find-links "$PROJECT_DIR/packages/wheels" "patroni[etcd3]==${PATRONI_VERSION}" "psycopg2-binary==2.9.5" "ydiff==1.4.2" cdiff
  else
    /opt/patroni-venv/bin/pip install --upgrade "pip<22"
    /opt/patroni-venv/bin/pip install "patroni[etcd3]==${PATRONI_VERSION}" "psycopg2-binary==2.9.5" "ydiff==1.4.2" cdiff
  fi
  ln -sf /opt/patroni-venv/bin/patroni /usr/local/bin/patroni
  ln -sf /opt/patroni-venv/bin/patronictl /usr/local/bin/patronictl
}

write_etcd_config() {
  local initial_cluster
  initial_cluster="$(etcd_initial_cluster)"
  cat >"$ETCD_CONFIG_FILE" <<EOF
name: ${MY_NAME}
data-dir: ${ETCD_DATA}/${MY_NAME}
initial-advertise-peer-urls: http://${MY_IP}:${ETCD_PEER_PORT}
listen-peer-urls: http://${MY_IP}:${ETCD_PEER_PORT}
listen-client-urls: http://${MY_IP}:${ETCD_CLIENT_PORT},http://127.0.0.1:${ETCD_CLIENT_PORT}
advertise-client-urls: http://${MY_IP}:${ETCD_CLIENT_PORT}
initial-cluster-token: ${CLUSTER_NAME}
initial-cluster: ${initial_cluster}
initial-cluster-state: new
logger: zap
log-outputs: [stderr]
EOF

  cat >/etc/systemd/system/etcd.service <<EOF
[Unit]
Description=etcd key-value store for PostgreSQL HA
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
ExecStart=${ETCD_BIN_DIR}/etcd --config-file ${ETCD_CONFIG_FILE}
Restart=on-failure
RestartSec=5
TimeoutStartSec=0
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
}

write_vip_callback() {
  cat >"$PATRONI_HOME/vip_callback.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail

ACTION="\${1:-}"
ROLE="\${2:-}"
VIP_ADDRESS="${VIP_ADDRESS}"
VIP_CIDR="${VIP_CIDR}"
VIP_DEVICE="${VIP_DEVICE}"
VIP_LABEL="${VIP_LABEL}"

[[ -n "\$VIP_ADDRESS" ]] || exit 0

has_vip() {
  /sbin/ip addr show dev "\$VIP_DEVICE" | grep -qw "\$VIP_ADDRESS"
}

add_vip() {
  if ! has_vip; then
    sudo /sbin/ip addr add "\${VIP_ADDRESS}/\${VIP_CIDR}" dev "\$VIP_DEVICE" label "\${VIP_DEVICE}:\${VIP_LABEL}"
    sudo /usr/sbin/arping -q -A -c 2 -I "\$VIP_DEVICE" "\$VIP_ADDRESS" || true
  fi
}

del_vip() {
  if has_vip; then
    sudo /sbin/ip addr del "\${VIP_ADDRESS}/\${VIP_CIDR}" dev "\$VIP_DEVICE" label "\${VIP_DEVICE}:\${VIP_LABEL}" || true
  fi
}

case "\$ACTION:\$ROLE" in
  on_start:master|on_start:primary|on_role_change:master|on_role_change:primary) add_vip ;;
  on_stop:master|on_stop:primary|on_role_change:replica|on_role_change:slave) del_vip ;;
esac
EOF
  chmod 0755 "$PATRONI_HOME/vip_callback.sh"
  chown "$POSTGRES_OS_USER:$POSTGRES_OS_USER" "$PATRONI_HOME/vip_callback.sh"

  if [[ -n "$VIP_ADDRESS" ]]; then
    cat >/etc/sudoers.d/postgres-patroni-vip <<EOF
${POSTGRES_OS_USER} ALL=(root) NOPASSWD: /sbin/ip, /usr/sbin/arping
EOF
    chmod 0440 /etc/sudoers.d/postgres-patroni-vip
  fi
}

write_patroni_config() {
  local etcd_hosts
  etcd_hosts="$(etcd_hosts_yaml)"
  cat >"$PATRONI_HOME/patroni.yml" <<EOF
scope: ${SCOPE}
namespace: /service/
name: ${MY_NAME}

restapi:
  listen: ${MY_IP}:${PATRONI_PORT}
  connect_address: ${MY_IP}:${PATRONI_PORT}

etcd3:
  hosts:
${etcd_hosts}

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: ${SYNCHRONOUS_MODE}
    synchronous_mode_strict: ${SYNCHRONOUS_MODE_STRICT}
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        listen_addresses: '*'
        port: ${POSTGRES_PORT}
        max_connections: ${MAX_CONNECTIONS}
        shared_buffers: ${SHARED_BUFFERS}
        effective_cache_size: ${EFFECTIVE_CACHE_SIZE}
        maintenance_work_mem: ${MAINTENANCE_WORK_MEM}
        work_mem: ${WORK_MEM}
        wal_level: replica
        wal_log_hints: 'on'
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: ${WAL_KEEP_SIZE}
        max_wal_size: ${MAX_WAL_SIZE}
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        hot_standby_feedback: 'on'
        password_encryption: scram-sha-256
        shared_preload_libraries: pg_stat_statements
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        logging_collector: 'on'
        log_directory: log
        log_filename: postgresql-%Y-%m-%d.log
        log_line_prefix: '%m [%p] %u@%d %r %a '
        log_min_duration_statement: 1000
        archive_mode: 'on'
        archive_command: 'test ! -f ${PG_WAL_ARCHIVE}/%f && cp %p ${PG_WAL_ARCHIVE}/%f'
  initdb:
    - encoding: UTF8
    - locale: C
    - data-checksums
  pg_hba:
    - host all all 0.0.0.0/0 scram-sha-256
    - host replication ${REPLICATION_USER} 0.0.0.0/0 scram-sha-256
  users:
    ${REWIND_USER}:
      password: ${REWIND_PASS}
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:${POSTGRES_PORT}
  connect_address: ${MY_IP}:${POSTGRES_PORT}
  data_dir: ${PG_DATA}
  bin_dir: ${PG_PREFIX}/bin
  config_dir: ${PG_DATA}
  pgpass: /home/${POSTGRES_OS_USER}/.pgpass
  authentication:
    superuser:
      username: ${POSTGRES_SUPERUSER}
      password: ${POSTGRES_SUPERPASS}
    replication:
      username: ${REPLICATION_USER}
      password: ${REPLICATION_PASS}
    rewind:
      username: ${REWIND_USER}
      password: ${REWIND_PASS}
  callbacks:
    on_start: ${PATRONI_HOME}/vip_callback.sh
    on_stop: ${PATRONI_HOME}/vip_callback.sh
    on_role_change: ${PATRONI_HOME}/vip_callback.sh
  parameters:
    unix_socket_directories: '/var/run/postgresql'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
EOF
  chown -R "$POSTGRES_OS_USER:$POSTGRES_OS_USER" "$PATRONI_HOME"
  chmod 0600 "$PATRONI_HOME/patroni.yml"
}

write_systemd() {
  cat >/etc/systemd/system/patroni.service <<EOF
[Unit]
Description=Patroni PostgreSQL HA manager
Wants=network-online.target etcd.service
After=network-online.target etcd.service

[Service]
Type=simple
User=${POSTGRES_OS_USER}
Group=${POSTGRES_OS_USER}
Environment=PATH=${PG_PREFIX}/bin:/opt/patroni-venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
ExecStart=/usr/local/bin/patroni ${PATRONI_HOME}/patroni.yml
Restart=on-failure
RestartSec=5
RuntimeDirectory=postgresql
RuntimeDirectoryMode=0775
TimeoutStopSec=600
LimitNOFILE=1024000
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target
EOF
}

configure_profile() {
  local pg_home
  pg_home="$(getent passwd "$POSTGRES_OS_USER" | cut -d: -f6)"
  [[ -n "$pg_home" ]] || pg_home="/home/${POSTGRES_OS_USER}"
  cat >/etc/profile.d/postgresql17.sh <<EOF
if [ "\$(id -un 2>/dev/null)" = "${POSTGRES_OS_USER}" ] && [ -f ${pg_home}/.pgev ]; then
  source ${pg_home}/.pgev
fi
EOF
}

start_services() {
  systemctl daemon-reload
  systemctl enable etcd patroni
  if [[ "${SKIP_SERVICE_START:-0}" == "1" ]]; then
    log "service start skipped by SKIP_SERVICE_START=1"
    return 0
  fi
  systemctl start --no-block etcd
  sleep 3
  systemctl start patroni
}

main() {
  install_prereqs
  configure_os
  configure_firewall
  create_users_dirs
  write_postgres_env
  install_postgres
  install_etcd
  install_patroni
  write_etcd_config
  write_vip_callback
  write_patroni_config
  write_systemd
  configure_profile
  start_services
  log "node $MY_NAME ($MY_IP) installed"
}

main "$@"
